BlogProjem.Web/Areas/Admin/Controllers/AppUserController.cs
using BlogProjem.Dal.Repositories.Interfaces.Concrete;
using BlogProjem.Model.Entities.Concrete;
using BlogProjem.Web.Areas.Admin.Models.DTOs;
using BlogProjem.Web.Areas.Admin.Models.VMs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BlogProjem.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class AppUserController : Controller
    {
        private readonly UserManager<IdentityUser> userManager;
        private readonly IAppUserRepository appUserRepository;
        private readonly IArticleRepository articleRepository;
        private readonly SignInManager<IdentityUser> signInManager;

        public AppUserController(UserManager<IdentityUser> userManager,IAppUserRepository appUserRepository,IArticleRepository articleRepository, 
            SignInManager<IdentityUser> signInManager)
        {
            this.userManager = userManager;
            this.appUserRepository = appUserRepository;
            this.articleRepository = articleRepository;
            this.signInManager = signInManager;
        }
        public IActionResult Abaut()
        {
            return View();
        }
       
        public async Task<IActionResult> Index()
        {

            //identity user kişisi
            IdentityUser identityUser = await userManager.GetUserAsync(User);
            AppUser appUser = appUserRepository.GetDefault(a => a.IdentityId == identityUser.Id);
            if (appUser != null)
            {
                var article = articleRepository.GetByDefaults
                    (selector: a=>new ArticleVm()
                    {
                      ID=a.ID,
                      AppUser=a.AppUser,
                      AppUserId=a.AppUserId,
                      Comments=a.Comments,
                      Content=a.Content,
                      CreatTime=a.CreatedDate,
                      ImagePath=a.ImagePath,
                      Likes=a.Likes,
                      Title=a.Title,
                      Views= a.views,
                      ReadingTime= a.Content.Length / 200,
                    },
                    expression:a=>a.Statu!=Model.Enums.Statu.Passive,
                    include:a=>a.Include(a=>a.AppUser).Include(a=>a.Comments).ThenInclude(a=>a.AppUser)
                    );
                return View(article);
            }
            return Redirect("~/");//areasız başlangıç sayfasına yani home-index
        }
        
        public IActionResult GetArticleIndex(int id)
        {

            //identity user kişisi
            
                var article = articleRepository.GetByDefaults
                    (selector: a => new ArticleVm()
                    {
                        ID = a.ID,
                        AppUser = a.AppUser,
                        AppUserId = a.AppUserId,
                        Comments = a.Comments.Where(a => a.Statu != Model.Enums.Statu.Passive).ToList(),
                        Content = a.Content,
                        CreatTime = a.CreatedDate,
                        ImagePath = a.ImagePath,
                        Likes = a.Likes,
                        Title = a.Title,
                        Views = a.views,
                        ReadingTime = a.Content.Length / 200,
                    },
                    expression: a => a.ArticleCategories.Any(a=>a.CategoryId==id),
                    include: a => a.Include(a => a.AppUser).Include(a => a.Comments).ThenInclude(a => a.AppUser).Include(a=>a.ArticleCategories).ThenInclude(a=>a.Category)
                    );
                return View(article);
            
           
        }
        [HttpGet]
        public async Task< IActionResult> UserDetail(int id)
        {
            AppUser appUser = appUserRepository.GetDefault(a => a.ID == id);
            IdentityUser identityUser = await userManager.FindByIdAsync(appUser.IdentityId);

            var UserProfil = appUserRepository.GetByDefault(selector: a => new GetUserDto()
            {
                id=a.ID,
                FirstName = a.FirstName,
                LastName = a.LastName,
                ImagePath = a.ImagePath,
                UserName = a.UserName,
                Email = identityUser.Email,
            }, expression: a => a.ID == id);

            return View(UserProfil);
        }
        [HttpPost]
        public IActionResult UserDetail(GetUserDto getUserDto)
        {
            var user = appUserRepository.GetDefault(a => a.ID == getUserDto.id);
            appUserRepository.Delete(user);
            return RedirectToAction("List");
        }

        public async Task< IActionResult> LogOut()
        {
            await signInManager.SignOutAsync();
            return Redirect("~/"); // yani areanın dışındaki anasayfaya demiş olduk
            
        }
        public IActionResult Edit()
        {
            return View();
        }
        public IActionResult List()
        {
            var AppUserList = appUserRepository.GetByDefaults(selector: a => new PassiveUserListDTO()
            {
                ID = a.ID,
                FirstName=a.FirstName,
                LastName=a.LastName,
                ImagePath=a.ImagePath,
                UserName=a.UserName
            },
            expression:a=>a.Statu==Model.Enums.Statu.Passive
            ) ;
            return View(AppUserList);
        }
        public IActionResult Active(int id)
        {
            var AppUser = appUserRepository.GetDefault(a => a.ID == id);
            AppUser.Statu = Model.Enums.Statu.Active;
            appUserRepository.Update(AppUser);
            return RedirectToAction("List");
        }

        public async Task< IActionResult> Profil()
        {
            IdentityUser identityUser = await userManager.GetUserAsync(User);
            var Admin=appUserRepository.GetDefault(a => a.IdentityId == identityUser.Id);

            var AdminProfil = appUserRepository.GetByDefault(selector: a => new GetUserDto()
            {
                id = a.ID,
                FirstName = a.FirstName,
                LastName = a.LastName,
                ImagePath = a.ImagePath,
                UserName = a.UserName,
                Email = identityUser.Email,
            }, expression: a => a.ID == Admin.ID );

            return View(AdminProfil);
        }
    }
}

BlogProjem.Web/Areas/Admin/Controllers/CommentController.cs
using BlogProjem.Dal.Repositories.Interfaces.Concrete;
using BlogProjem.Web.Areas.Admin.Models.VMs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BlogProjem.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class CommentController : Controller
    {
        private readonly IArticleRepository articleRepository;
        private readonly ICommentRepository commentRepository;

        public CommentController(IArticleRepository articleRepository,ICommentRepository commentRepository)
        {
            this.articleRepository = articleRepository;
            this.commentRepository = commentRepository;
        }
        public IActionResult List(int id)
        {
            var article = articleRepository.GetByDefault
                (
                selector: a=> new CommentArticleVm()
                {
                    ArticleId = id,
                    AppUser=a.AppUser,
                    AppUserId=a.AppUserId,
                    Comments=a.Comments.Where(a=>a.Statu!=Model.Enums.Statu.Passive).ToList(),
                    Title=a.Title,
                    Content=a.Content,
                    ImagePath=a.ImagePath,
                    CreatedDate=a.CreatedDate,
                    Likes=a.Likes,
                    views=a.views
                },
                expression:a=>a.ID==id,
                 include: a => a.Include(a => a.Comments).ThenInclude(a => a.AppUser).Include(a => a.AppUser)
                );

            return View(article);
        }
        public IActionResult Passive(int id,int id2)
        {
            var comment = commentRepository.GetDefault(a=>a.ID==id);
            //comment.Statu=Model.Enums.Statu.Passive;
            commentRepository.Delete(comment);
            return RedirectToAction("List", new { id = id2 });
        }

        


    }
}

BlogProjem.Web/Areas/Admin/Views/AppUser/Abaut.cshtml
<div class="col-md-12">
    <div>
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3006.109435421134!2d29.022254915354054!3d41.11030097929056!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14cab58f4c1b6127%3A0xd31c6b954078684a!2sBilgeAdam%20Maslak!5e0!3m2!1str!2str!4v1663499402395!5m2!1str!2str" width="100%" height="435" frameborder="0" style="border:0" allowfullscreen></iframe>
    </div>
</div>


<!--starrrrttttttttttttttttttttttttttttttttttttt-->
<div class="col-md-6 ">
    <form action="" method="">
        <div class="card mt-4">
            <div class="card-body p-3">
                <div class="form-group">
                    <h3>iletişim formu</h3>
                </div>

                <div class="form-group">
                    <div class="input-group mb-2">
                        <div class="input-group-prepend">
                            <div class="input-group-text">
                                <i class="fa fa-user text-info"></i>
                            </div>
                        </div>
                        <input type="text" class="form-control" name="" placeholder="Ad Soyad" required>
                    </div>
                </div>
                <div class="form-group">
                    <div class="input-group mb-2">
                        <div class="input-group-prepend">
                            <div class="input-group-text">
                                <i class="fa fa-envelope text-info"></i>
                            </div>
                        </div>
                        <input type="email" class="form-control" name="" placeholder="E-Posta" required>
                    </div>
                </div>
                <div class="form-group">
                    <div class="input-group mb-2">
                        <div class="input-group-prepend">
                            <div class="input-group-text">
                                <i class="fa fa-tag text-info"></i>
                            </div>
                        </div>
                        <input type="text" class="form-control" name="" placeholder="Konu" required>
                    </div>
                </div>
                <div class="form-group">
                    <div class="input-group mb-2">
                        <div class="input-group-prepend">
                            <div class="input-group-text">
                                <i class="fa fa-comment text-info"></i>
                            </div>
                        </div>
                        <textarea class="form-control" placeholder="Lütfen Mesajınızı Buraya Yazın.." rows="6" required></textarea>
                    </div>
                </div>
                <div class="text-center">
                    <input id="btn1" type="submit" value="GÖNDER" class="btn btn-info btn-block">
                </div>
            </div>
        </div>
    </form>
</div>
<div class="col-md-6">
    <div class="col-sm-10">
        <div class="offset-sm-3">
    <div class="mt-4">
        <div class="bg-cyan">
            <h3>Bilge Adam Nerede?</h3>
            <p class="font-italic">
                <i class="fas fa-map-marker-alt"></i>
                Noramin İş Merkezi Kat:5 Büyükdere Caddesi No:237 Maslak – Sarıyer / İSTANBUL
            </p>



        </div>


    </div>
    </div>
    </div>
</div>

BlogProjem.Web/Areas/Admin/Views/AppUser/GetArticleIndex.cshtml
@model List<ArticleVm>

@foreach (var item in Model)
{
    <div class="col-md-6">
        <div class="card card-widget">
            <div class="card-header">
                <div class="user-block">
                    <img class="img-circle" style="border-radius:50%;" src="@item.AppUser.ImagePath" alt="User Image">
                    <span class="username"><a asp-controller="AppUser" asp-action="detail" asp-route-id="@item.AppUserId">@item.AppUser.FirstName @item.AppUser.LastName</a></span>
                    <span class="description">Tarafından Paylaşıldı - @item.CreatTime.ToString("dd MMMM dddd yyyy")</span>
                </div>
                <!-- /.user-block -->
                <!-- /.card-tools -->
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <img class="img-fluid pad" src="@item.ImagePath" alt="makalenni resmi">
                <p><b>@item.Title</b></p>@*makalenin başlıgı*@
                <p> 
                   @for (int i = 0; i <item.Content.Split(' ','.',',').Length; i++)
                    {
                        @item.Content[i]
                    }
                </p>
                <a asp-controller="Comment" asp-action="List" asp-route-id="@item.ID">Devamını okumak için tıklayınız !...</a>
                <span class="float-right text-muted">Begeni: @item.Likes.Count() - Yorum: @item.Comments.Count()</span> <br>
                <span class="float-right text-muted">Görüntülenme @item.Views</span> <br>
                <span class="float-right text-muted">Okunma Süresi @item.ReadingTime Dakika</span>
            </div>
            <!-- /.card-body -->
            @if (item.Comments.Count > 0)
            {
                @foreach (var comment in item.Comments.OrderByDescending(a=>a.CreatedDate).Take(3))
                {
                    <div class="card-footer card-comments">
                        <div class="card-comment">
                            <!-- User image -->
                            <a asp-controller="AppUser" asp-action="detail" asp-route-id="@comment.AppUserId"> <img class="img-circle img-xsm" style="border-radius:50%;"
                                src="@comment.AppUser.ImagePath " alt="User Image"> </a>
                            <div class="comment-text">
                                <span class="username">
                                    @comment.Text
                                    <span class="text-muted float-right">@comment.CreatedDate.ToString()</span>
                                </span>
                                
                            </div>
                        </div>
                    </div>
                }
            }
        </div>
    </div>
}

BlogProjem.Web/Areas/Admin/Views/AppUser/Index.cshtml
@model List<ArticleVm>

@foreach (var item in Model)
{
    <div class="col-md-6">
        <div class="card card-widget">
            <div class="card-header">
                <div class="user-block">
                    <img class="img-circle" style="border-radius:50%;" src="@item.AppUser.ImagePath" alt="User Image">
                    <span class="username"><a asp-controller="AppUser" asp-action="UserDetail" asp-route-id="@item.AppUserId">@item.AppUser.FirstName @item.AppUser.LastName</a></span>
                    <span class="description">Tarafından Paylaşıldı - @item.CreatTime.ToString("dd MMMM dddd yyyy")</span>
                </div>
                <!-- /.user-block -->
                <!-- /.card-tools -->
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <img class="img-fluid pad" src="@item.ImagePath" alt="makalenni resmi">
                <p><b>@item.Title</b></p>@*makalenin başlıgı*@
                <p> 
                   @for (int i = 0; i <item.Content.Split(' ','.',',').Length; i++)
                    {
                        @item.Content[i]
                    }
                </p>
                <a asp-controller="Comment" asp-action="List" asp-route-id="@item.ID">Devamını okumak için tıklayınız !...</a>
                <span class="float-right text-muted">Begeni: @item.Likes.Count() - Yorum: @item.Comments.Count()</span> <br>
                <span class="float-right text-muted">Görüntülenme @item.Views</span> <br>
                <span class="float-right text-muted">Okunma Süresi @item.ReadingTime Dakika</span>
            </div>
            <!-- /.card-body -->
            @if (item.Comments.Count > 0)
            {
                @foreach (var comment in item.Comments.OrderByDescending(a=>a.CreatedDate).Take(3))
                {
                    <div class="card-footer card-comments">
                        <div class="card-comment">
                            <!-- User image -->
                            <a asp-controller="AppUser" asp-action="UserDetail" asp-route-id="@comment.AppUserId"> <img class="img-circle img-xsm" style="border-radius:50%;"
                                src="@comment.AppUser.ImagePath " alt="User Image"> </a>
                            <div class="comment-text">
                                <span class="username">
                                    @comment.Text
                                    <span class="text-muted float-right">@comment.CreatedDate.ToString()</span>
                                </span>
                                
                            </div>
                        </div>
                    </div>
                }
            }
        </div>
    </div>
}

BlogProjem.Web/Areas/Admin/Views/AppUser/List.cshtml
@model List<PassiveUserListDTO>
@foreach (var item in Model)
{
    <div class="card" style="width: 18rem;">
  <img src="@item.ImagePath" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">@item.FullName</h5>
    <p class="card-text">@item.UserName</p>
    <a asp-action="Active" asp-route-id="@item.ID" class="btn btn-primary">Hesabı Aktif Et</a>
  </div>
</div>
    
}

BlogProjem.Web/Areas/Admin/Views/AppUser/Profil.cshtml
@model GetUserDto 

<div class="card-body p-0">
    <table class="table">
        <thead>
           <tr>                      
             <th>ADINIZ</th>
             <th>SOYADINIZ</th>
             <th>Profil Resmi</th>
             <th>Email</th>
             <th>Kullanıcı Adınız</th>                      
           </tr>
        </thead>
        <tbody>
            <tr>
                <td class="text-bold text-black">@Model.FirstName</td>
                <td class="text-bold text-black">@Model.LastName</td>
                <td> <img src="@Model.ImagePath"/> </td>
                <td class="text-bold text-black">@Model.Email</td>
                <td class="text-bold text-black">@Model.UserName</td>
            </tr>
        </tbody>
    </table>
</div>

BlogProjem.Web/Areas/Admin/Views/AppUser/UserDetail.cshtml
@model GetUserDto

<form asp-action="UserDetail" method="post">
 <div class="card-body p-0">
    <table class="table">
        <thead>
           <tr>                      
             <th>ADINIZ</th>
             <th>SOYADINIZ</th>
             <th>Profil Resmi</th>
             <th>Email</th>
             <th>Kullanıcı Adınız</th>                      
           </tr>
        </thead>
        <tbody>
            <tr>
                <td class="text-bold text-black">@Model.FirstName</td>
                <td class="text-bold text-black">@Model.LastName</td>
                <td> <img src="@Model.ImagePath"/> </td>
                <td class="text-bold text-black">@Model.Email</td>
                <td class="text-bold text-black">@Model.UserName</td>
            </tr>
        </tbody>
    </table>
     <button type="submit" class="btn btn-primary"> Hesabı Dondur </button> 
</div>
</form>